export interface ListConfig {
  ANDROID_VERSION: string;
  IOS_VERSION: string;
  LANGUAGE_VERSION: number;
  DURATION_EXPIRED: number;
  DISCOUNT_PRICE_SUB_MENU: number;
  DISCOUNT_SUB_MENU_SECOND: number;
  POINT_REFERAL: number;
  POINT_REFUND_BOOKING: number;
  POINT_ADD_FEEDBACK: number;
  POINT_REFERAL_FIRST_BOOKING_BODY_REMOVAL: number;
  POINT_REFERAL_FIRST_BOOKING_REMOVAL: number;
  POINT_REFERAL_FIRST_BOOKING_DRNS: number;
  POINT_REFERAL_TICKET: number;
  POINT_EXCHANGE_RATE: number;
  POINT_WITHDRAW_RATE: number;
  POINT_PER_PACKAGE: number;
  POINT_REFERAL_LP: number;
}
